# SPDX-FileCopyrightText: 2024 CSC - IT Center for Science Ltd. <www.csc.fi>
#
# SPDX-License-Identifier: MIT

name: Build HTML and PDF slides

on:
  # Uncomment the following block to activate PDF build for all pushes
  # push:
  #   branches:
  #     - "*"
  #   paths:
  #     - "**/docs/**"
  #     - "**/about.yml"
  #     - ".github/workflows/pages*.yml"
  workflow_dispatch:

permissions:
  contents: read

# Cancel in-progress builds for new pushes to the branch
concurrency:
  group: pages-build-pdf-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  pages:
    uses: ./.github/workflows/pages-build.yml
    with:
      include_pdf: true
